2109 localwork
ContactEngineering/zoomdata pull request #1
Opened 2023-09-21 14:52 UTC by Adityapadmanair

This is the newly created branch with the Bokeh issue. Please take a look.

2023-09-22 23:53 UTC, pastewka requested changes

2023-09-22 23:53 UTC, pastewka commented on package.json
> +    "bokehjs": "^1.4.0",
This dependency should be removed

2023-09-22 23:53 UTC, pastewka commented on src/main.js
> +import * as Bokeh from 'bokehjs';
You don't need this import. 'bokehjs' is not the Bokeh plotting library.

2023-09-22 23:53 UTC, pastewka commented on src/main.js
> +                ctx.fillStyle = color;
`color` is an integer. You need to turn that into a HTML color code: `ctx.fillStyle = '#'+(color.toString(16).substring(0, 6));`

2023-09-24 13:46 UTC, Adityapadmanair commented
Doing a new pull req with the above mentioned changes

2023-09-24 13:46 UTC, closed without merging